### ISSUE TITLE
Installing dot net 4.5.2 does not work remotely (over winrm)

### ISSUE THREAD

**Issue by tophercullen** [criteo-cookbooks/ms_dotnet#13]
The 4.5.2 installer uses WUSA which is restricted for remote shells. Trying to bootstrap or run chef-client of winrm results in a failure "Access denied" during the install. This issue could apply to all other installs as well, but haven't confirmed. The only workarounds I've found are 
1. don't run it remote for the first run
2. use psexec for the installer
I have a pull requests I can submit, but its a great departure from using windows_package

**Comment by Annih** [comment]
Hello @tophercullen 

Thanks for your participation, but I'm sorry I'll not fix this issue because this is actually a known issue that is not related to ms_dotnet cookbook. It is due to the way you try to run chef or at least apply ms_dotnet recipes.

I recommend you to try to run chef-client via a Schedule task, allowing you to remotely run as SYSTEM with all elevation privileges!

I'll try to retrieve all similar topic in related technologies:
* [test-kitchen#876](https://github.com/test-kitchen/test-kitchen/issues/876)
* [knife-windows#318](https://github.com/chef/knife-windows/issues/318)

**Comment by tophercullen** [comment]
I understand. Whether or not you accept it as a problem with the cookbook, winrm is the opscode documented way on interacting with windows systems. This is going to cause a problem for nearly anyone who uses your cookbook at scale. This is particularly true for bootstrapping a new node since the bootstrap runlist will need to be different or changed later to the final run list that includes the problem recipes. It would be a good idea to indicate this limitation/requirement so people aren't left scratching their heads.

**Comment by Annih** [comment]
I'm sorry, but again this is not a limitation of this cookbook but of knife bootstrap or chef-provisioning.
Winrm is a good remoting system on Windows I recommend it everywhere, but due to its limitation gem implementing this transport have to provide a way to synchronously run a remote command as a local one with elevated privilege.
Vagrant winrm transport is providing this way, winrm-elevated gem is providing this way, we just have to wait that test-kitchen knife-windows and chef-provisioning use this gem...

As a "ms_dotnet" cookbook maintainer it's not possible for me to handle all way people are using my recipes.

However I [added a note](https://github.com/criteo-cookbooks/ms_dotnet#known-issues) in the README to explain a bit this issue. Is it clear enough for you?

**Comment by tophercullen** [comment]
I understand you can't code for everything. However, saying this supports Chef 11 is misleading as you know it doesn't work with the official chef tools in a major documented use. Thank you noting this in the about. Could you also include that 'knife winrm' subcomand is also effected? e.g 'Common environment: knife windows bootstrap, knife winrm, chef-provisioning, test-kitchen'

**Comment by tophercullen** [comment]
with regards to the gem, can you link to where this is be reported as an issue?
