### ISSUE TITLE
Having issue with 3.0.0 and windows8.1-kb2919442-x64.msu

### ISSUE THREAD

**Issue by bveselka** [criteo-cookbooks/ms_dotnet#29]
I get the following when upgraded to 3.0.0 from 2.6.1.  This is being run on a 2012 R2 server.

I am installing .Net 4.6.1

ms_dotnet_framework[4.6.1](ms_dotnet::ms_dotnet4 line 24) had an error: Mixlib::ShellOut::ShellCommandFailed: windows_package[Update for Microsoft Windows (KB2919442)](c:/chef/cache/cookbooks/ms_dotnet/providers/framework.rb line 53) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 3010], but received '-2145124329' ---- Begin output of start "" /wait "c:\chef\cache\package\windows8.1-kb2919442-x64.msu" /norestart /quiet & exit %%%%ERRORLEVEL%%%% ---- STDOUT: STDERR: ---- End output of start "" /wait "c:\chef\cache\package\windows8.1-kb2919442-x64.msu" /norestart /quiet & exit %%%%ERRORLEVEL%%%% ---- Ran start "" /wait "c:\chef\cache\package\windows8.1-kb2919442-x64.msu" /norestart /quiet & exit %%%%ERRORLEVEL%%%% returned -2145124329

**Comment by Matasx** [comment]
I have also experienced this. According to this page https://social.technet.microsoft.com/Forums/sharepoint/en-US/1a43f431-8333-430a-b52b-67bb27d77ecb/install-net-framework-46-on-server-2012r2?forum=winserver8gen the KB3021910 should be used as a replacement of KB2919442.

**Comment by Annih** [comment]
Should be fixed by #31, let's reopen if this is not fixed.

**Comment by lbn-aaio-team** [comment]
Hello,

I met an error with windows 2012 R2 full updated and cookbook 3.1.0 ms_dotnet when installing .NET 4.6.1:

STDERR:
---- End output of start "" /wait "c:\chef\cache\package\windows8.1-kb3021910-x64.msu"   /norestart /quiet & exit %%%%ERRORLEVEL%%%% ----
Ran start "" /wait "c:\chef\cache\package\windows8.1-kb3021910-x64.msu"   /norestart /quiet & exit %%%%ERRORLEVEL%%%% returned 1618

This dependency (kb3021910) cannot be installed because this update is replaced by KB3173424 since 11/07/2016 as shown here:
http://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=07a0954d-ee90-4c6c-b017-47837af9c5ba

Best regards,
