### ISSUE TITLE
Reboot after dependencies installation

### ISSUE THREAD

**Issue by olivierlemasle** [criteo-cookbooks/ms_dotnet#32]
How to reboot when a reboot is required between the installation of a dependency and the installation of .NET?

(NB: issue #30 was specific to reboot after .NET installation)

Last July, I've already had this issue (https://github.com/criteo-cookbooks/ms_dotnet/pull/27#issuecomment-233684470) but I solved it by using the Windows Reboot Handler provided by the windows cookbook, as suggested in commit message 7716fc98fcc.

However, resource `windows_reboot` and reboot handler were removed from version 2.0.0 of the windows cookbook. `windows_reboot` can be replaced by the `reboot` resource in Chef 12.1+, but how to configure a reboot handler?

I tried to update the `ms_dotnet` cookbook by:

- using `reboot` resource (Chef 12.1+):

      reboot ms_dotnet do
        action :nothing
      end

- and adding

      notifies :reboot_now, "reboot[ms_dotnet]", :immediately if reboot_pending?

   to `windows_package`. However, `reboot_pending?` seems to always be `false`, even when the installation of `ndp46-kb3045557-x86-x64-allos-enu.exe` is explicitly rejected because of the lack of reboot after KB2919355 installation.

**Comment by Annih** [comment]
Hello @olivierlemasle 

Thank you for this clear and detailed issue.
I was already considering adding a `reboot` resource between every package setup of the `ms_dotnet_framework` resource.

The implementation provided in #35 should be close to what you are describing, but without the tiny bug you faced :)

`reboot_pending?` returns false in your case because it is evaluated when the package resource is created. To fix the issue you need to delay the evaluation of `reboot_pending` just before the `reboot` resource is evaluated, in the `only_if` or `not_if` guard for instance.

Take a look at my PR, and play with it if you can, it should fix your issue.

Regards!

**Comment by olivierlemasle** [comment]
Hi @Annih,

Thanks for the pull request; I'm testing it and I'll come back to you.

**Comment by olivierlemasle** [comment]
Thanks @Annih, pull request #35 fixes my issue indeed.

**Comment by Annih** [comment]
Thanks for your tests and feedbacks @olivierlemasle I'll release a new version soon :)
