### ISSUE TITLE
Unable to use DevPack for .Net installation due to lookup via checksum

### ISSUE THREAD

**Issue by taliesins** [criteo-cookbooks/ms_dotnet#78]
Packages are based on their checksum and not their name:
https://github.com/criteo-cookbooks/ms_dotnet/blob/master/resources/framework.rb#L92

So if we do the following:
`package_sources(node['ms_dotnet']['4.7.1']['checksum'] => node['ms_dotnet']['4.7.1']['url'])`

as checksum is hard coded value in cookbook, I wont be able to do this:

```
default['ms_dotnet']['4.7.1']['checksum'] = 'a615488d2c5229aff3b97c56f7e5519cc7ac4f58b638a8e159b19c5c3d455c7b'
default['ms_dotnet']['4.7.1']['url'] = "#{software_installation_path}DotNetFramework/NDP471-DevPack-ENU.exe"
```

Could we rather lookup package sources based on their name:
```
package_sources( 'Microsoft .NET Framework 4.7.1' =>
{
          url: node['ms_dotnet']['4.7.1']['url'],
          checksum: node['ms_dotnet']['4.7.1']['checksum'],
}
)
```

**Comment by Annih** [comment]
Hello @taliesins 

I understand that you want to setup .NET 4.7 with the DevPack, however this cookbook is not intended to do it. The main goal of this cookbook is to ease installation of the Official .NET Framework, not its dev pack.

The Development pack is not the same "package" as the .NET Framework, it does not install the same things. Here is Microsoft description:
> The Microsoft Framework 4.7.1 Developer Pack installs the .NET Framework 4.7.1, the .NET 4.7.1 Targeting Pack and the .NET 4.7.1 SDK. 

This is a 3-in-1 package, trying to handle them is not that easy. What should you do on a Windows 10 1709 machine, coming with .NET 4.7.1?
1. do nothing because the feature is already here?
2. check for all packages + the feature ?

There is a way to do what you want, but I won't explain it because this is hacky and  would break the idempotency of the resource.
On the other hand I can suggest you to install the .NET Framework using this cookbook, **then** install the dev package:
```ruby
include_recipe 'ms_dotnet::msdotnet4'
package 'Microsoft .NET Framework 4.7.1 SDK' do
  source 'https://download.microsoft.com/download/9/0/1/901B684B-659E-4CBD-BEC8-B3F06967C2E7/NDP471-DevPack-ENU.exe'
  checksum 'a615488d2c5229aff3b97c56f7e5519cc7ac4f58b638a8e159b19c5c3d455c7b'
end
```

This increase the downloaded payload, but at least you'll be sure that both Framework & devpack will be setup correctly.
